# Generated by Django 2.2 on 2019-05-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='direccion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lt',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lote',
            name='mz',
            field=models.CharField(max_length=10),
        ),
    ]
